BAH 2962 | EVentListener to send SMS to the user
Bahmni/openmrs-module-communication pull request #7
Opened 2023-09-13 10:22 UTC by anubhavBeehyv

- Added an event listener to listen to the events coming up from bahmni-events module
- Events on which sms is send as for now are patient creation,appointment booking(recurring,regular).
- Added an appointment reminder sms feature in the same (working as a part of scheduler).

2023-09-13 10:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Bahmni/openmrs-module-communication?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Bahmni/openmrs-module-communication?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Bahmni/openmrs-module-communication?pullRequest=7) it.</sub>

2023-10-05 12:17 UTC, angshu requested changes

2023-10-05 12:17 UTC, angshu commented on api/pom.xml
> +            <version>4.5.14</version>
scope should be provided

2023-10-05 12:17 UTC, angshu commented on api/src/main/java/org/bahmni/module/communication/service/impl/CommunicationServiceImpl.java
> +			String tokenFilePath = new File("/tmp/sms-tokens", SMS_TOKEN_KEY + "-token.txt").getAbsolutePath();
should be reading from a file available under OMRS application data directory

2023-10-05 12:17 UTC, angshu commented on api/src/main/java/org/bahmni/module/communication/service/impl/CommunicationServiceImpl.java
> +			CloseableHttpClient httpClient = HttpClients.createDefault();
maybe better done leveraging closeable interface. Check https://www.baeldung.com/apache-httpclient-vs-closeablehttpclient

2023-10-05 12:17 UTC, angshu commented on api/src/main/resources/liquibase.xml
> +<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
do we need this? if not, remove

2023-10-05 12:17 UTC, angshu commented on api/src/main/resources/messages.properties
> +bahmni.sms.url=http://sms-service:8080/notification/sms
Why is the sms server url here? it should be in global property. If the property is not found - log error.

2023-10-17 13:27 UTC, angshu approved these changes

2023-10-17 13:28 UTC, angshu commented
You have lowered the ratio, which is ok for now but please create a card on JIRA to improve test coverage for this module.

2023-10-17 13:29 UTC, anubhavBeehyv commented
> You have lowered the ratio, which is ok for now but please create a card on JIRA to improve test coverage for this module.

Sure @angshu

2023-10-19 06:52 UTC, merged